{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "08de60e6-8993-4130-9d28-fdfc948da00c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)\n",
      "ERROR: No matching distribution found for tkinter\n"
     ]
    }
   ],
   "source": [
    "pip install tkinter "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "be4b44ea-c22f-4697-8098-d681d0400ec0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cc923f6d-cad1-4095-9134-d8d8c12be075",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "cbb997f4-0cfb-4d9a-9d2b-25354b5157b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "root = Tk()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0fa69cd0-9e81-416c-b646-7db11b80e742",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Creating a Label Widget\n",
    "myLabel = Label(root, text=\"Hello World!\") "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e460ce29-0948-4e59-a935-1f9097148f8f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Shoving it onto the screen\n",
    "myLabel.pack()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29aab4b6-67b5-4a44-843d-e16f1b5499c6",
   "metadata": {},
   "outputs": [],
   "source": [
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c73c2191-add6-45ba-9a77-f40e5fc6b762",
   "metadata": {},
   "outputs": [],
   "source": [
    "#creating a new tkinter window \n",
    "\n",
    "master = tk.Tk()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1b9eeb6-8104-46bb-8c93-730f1da70420",
   "metadata": {},
   "outputs": [],
   "source": [
    "#assigning a title \n",
    "master.title(\"Pricing Analysis\") "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "436a19f6-8f4c-4145-b013-ad6dedbe14a5",
   "metadata": {},
   "outputs": [],
   "source": [
    "#specifying geometry for window size \n",
    "master.geometry(\"700x250\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a3374dec-4b9a-40f0-88e2-c7ed2b046123",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 37, in submit_form\n",
      "    save_to_excel(name, email, age, occupation)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\Temp\\ipykernel_69488\\155651048.py\", line 24, in save_to_excel\n",
      "    workbook.save(file_name)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 386, in save\n",
      "    save_workbook(self, filename)\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n",
      "    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\kgupta\\AppData\\Local\\miniconda3\\Lib\\zipfile.py\", line 1284, in __init__\n",
      "    self.fp = io.open(file, filemode)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "PermissionError: [Errno 13] Permission denied: 'form_output.xlsx'\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "import openpyxl\n",
    "from openpyxl import Workbook\n",
    "\n",
    "# Function to save form data into an Excel file\n",
    "def save_to_excel(name, email, age, occupation):\n",
    "    file_name = \"form_output.xlsx\"\n",
    "    \n",
    "    # Create a new workbook and add data\n",
    "    try:\n",
    "        workbook = openpyxl.load_workbook(file_name)\n",
    "        sheet = workbook.active\n",
    "    except FileNotFoundError:\n",
    "        workbook = Workbook()\n",
    "        sheet = workbook.active\n",
    "        # Create headers for new sheet\n",
    "        sheet.append([\"Name\", \"Email\", \"Age\", \"Occupation\"])\n",
    "\n",
    "    # Add form data\n",
    "    sheet.append([name, email, age, occupation])\n",
    "    \n",
    "    # Save the workbook\n",
    "    workbook.save(file_name)\n",
    "    messagebox.showinfo(\"Success\", f\"Data saved to {file_name}\")\n",
    "\n",
    "# Function to be called when the form is submitted\n",
    "def submit_form():\n",
    "    name = name_entry.get()\n",
    "    email = email_entry.get()\n",
    "    age = age_entry.get()\n",
    "    occupation = occupation_entry.get()\n",
    "    \n",
    "    if not name or not email or not age or not occupation:\n",
    "        messagebox.showwarning(\"Input Error\", \"Please fill all the fields!\")\n",
    "    else:\n",
    "        save_to_excel(name, email, age, occupation)\n",
    "        clear_form()\n",
    "\n",
    "# Function to clear the form after submission\n",
    "def clear_form():\n",
    "    name_entry.delete(0, tk.END)\n",
    "    email_entry.delete(0, tk.END)\n",
    "    age_entry.delete(0, tk.END)\n",
    "    occupation_entry.delete(0, tk.END)\n",
    "\n",
    "# Set up the GUI window\n",
    "root = tk.Tk()\n",
    "root.title(\"User Information Form\")\n",
    "\n",
    "# Create form labels and entries\n",
    "tk.Label(root, text=\"Name\").grid(row=0, column=0, padx=10, pady=10)\n",
    "name_entry = tk.Entry(root)\n",
    "name_entry.grid(row=0, column=1, padx=10, pady=10)\n",
    "\n",
    "tk.Label(root, text=\"Email\").grid(row=1, column=0, padx=10, pady=10)\n",
    "email_entry = tk.Entry(root)\n",
    "email_entry.grid(row=1, column=1, padx=10, pady=10)\n",
    "\n",
    "tk.Label(root, text=\"Age\").grid(row=2, column=0, padx=10, pady=10)\n",
    "age_entry = tk.Entry(root)\n",
    "age_entry.grid(row=2, column=1, padx=10, pady=10)\n",
    "\n",
    "tk.Label(root, text=\"Occupation\").grid(row=3, column=0, padx=10, pady=10)\n",
    "occupation_entry = tk.Entry(root)\n",
    "occupation_entry.grid(row=3, column=1, padx=10, pady=10)\n",
    "\n",
    "# Submit button\n",
    "submit_btn = tk.Button(root, text=\"Submit\", command=submit_form)\n",
    "submit_btn.grid(row=4, columnspan=2, pady=10)\n",
    "\n",
    "# Run the Tkinter event loop\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8664180-689f-4f97-b6cc-8194d124092c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "etl-env",
   "language": "python",
   "name": "etl-env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
